# action.yml
name: MIE LaunchPad
description: Manage Proxmox MIE Containers for your Repository.
author: maxklema
branding:
  icon: 'rocket'
  color: 'purple'

inputs:
  container_password:
    description: 'Password for your LXC Container'
    required: true
  proxmox_password:
    description: 'Password for your MIE Proxmox Account'
    required: true
  github_event_name:
    description: 'GitHub Event Name (create, push, delete)'
    required: true
  github_repository:
    description: 'GitHub Repository (owner/repo)'
    required: true
  github_repository_owner:
    description: 'GitHub Repository Owner'
    required: true
  github_ref_name:
    description: 'GitHub Ref Name (Branch Name)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Container Creation for Branch (If Needed)
      id: create-lxc
      env:
        GITHUB_EVENT: ${{ inputs.github_event_name }}
        CONTAINER_NAME: ${{ inputs.github_repository }}-${{ inputs.github_repository_owner }}-${{ inputs.github_ref_name }}
        CONTAINER_PASSWORD: ${{ inputs.container_password }}
        PROXMOX_USERNAME: mklema
        PROXMOX_PASSWORD: ${{ inputs.proxmox_password }}
        HTTP_PORT: 32000
        DEPLOY_ON_START: y
        PROJECT_REPOSITORY: https://github.com/maxklema/rankroom
        PROJECT_BRANCH: ${{ inputs.github_ref_name }}
        PROJECT_ROOT:
        REQUIRE_ENV_VARS: y
        CONTAINER_ENV_VARS: '{"API_KEY": "1234"}'
        INSTALL_COMMAND: npm i
        START_COMMAND: npm start
        BUILD_COMMAND:
        RUNTIME_LANGUAGE: nodejs
        REQUIRE_SERVICES: y
        SERVICES: '["mongodb"]'
      if: ${{ inputs.github_event_name == 'create' || inputs.github_event_name == 'push' }}
      run: bash .github/lxc-creation-logic.sh

    - name: Container Update on Branch Push
      if: ${{ inputs.github_event_name == 'push' }}
      run: |
        ssh -i ~/.ssh/id_rsa \
          -o SendEnv="CONTAINER_NAME PROXMOX_USERNAME PROXMOX_PASSWORD PROJECT_REPOSITORY PROJECT_BRANCH PROJECT_ROOT INSTALL_COMMAND START_COMMAND BUILD_COMMAND RUNTIME_LANGUAGE" \
          update-container@10.15.0.4
        exit $?

    - name: Container Deletion on Branch Deletion (Check)
      if: ${{ inputs.github_event_name == 'delete' }}
      run: |
        ssh -i ~/.ssh/id_rsa \
          -o SendEnv="PROXMOX_USERNAME PROXMOX_PASSWORD CONTAINER_NAME" delete-container@10.15.0.4
        exit $?
