name: MIE Proxmox Container Management

# Triggers on branch push, creation, or deletion
on:
  create:
    branches:
      - '**'
  push:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  Manage-Container:
    runs-on: self-hosted
    env:
      CONTAINER_NAME: ${{ github.event.repository.name }}-${{ github.event.actor.login }}-${{ github.ref_name }}
      CONTAINER_PASSWORD: ${{ secrets.CONTAINER_PASSWORD }}
      PROXMOX_USERNAME: mklema
      PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
      HTTP_PORT: 32000
      DEPLOY_ON_START: y
      PROJECT_REPOSITORY: https://github.com/maxklema/rankroom
      PROJECT_BRANCH: ${{ github.ref_name }}
      PROJECT_ROOT:
      REQUIRE_ENV_VARS: y
      CONTAINER_ENV_VARS: '{"API_KEY": "1234"}'
      INSTALL_COMMAND: npm i
      START_COMMAND: npm start
      BUILD_COMMAND: 
      RUNTIME_LANGUAGE: nodejs
      REQUIRE_SERVICES: y
      SERVICES: '["mongodb"]'
    
    steps:
     - name: Container Creation for Branch (If Needed)
       id: create-lxc
       if: github.event_name == 'create' || github.event_name == 'push'
       run: |
        # check if container exists
        ssh -i ~/.ssh/id_rsa -o SendEnv="PROXMOX_USERNAME PROXMOX_PASSWORD CONTAINER_NAME" container-exists@10.15.0.4
        CONTAINER_EXISTS=$?
        if [ $CONTAINER_EXISTS -eq 0 ] || [ $CONTAINER_EXISTS -eq 2 ] ; then
          echo "Container \"$CONTAINER_NAME\" already found with this name. Cannot create container on this branch."
        elif [ $CONTAINER_EXISTS -eq 1 ]; then
          echo "Container \"$CONTAINER_NAME\" Not Found. Creating Container based on ${{ github.ref_name }}"
          
          # continue if an exit code error in remote container creation script
          set +e

          TMP_OUTPUT=$(mktemp)
          ssh -i ~/.ssh/id_rsa \
            -o SendEnv="CONTAINER_NAME CONTAINER_PASSWORD PROXMOX_USERNAME PROXMOX_PASSWORD HTTP_PORT DEPLOY_ON_START PROJECT_REPOSITORY PROJECT_BRANCH PROJECT_ROOT REQUIRE_ENV_VARS CONTAINER_ENV_VARS INSTALL_COMMAND START_COMMAND RUNTIME_LANGUAGE REQUIRE_SERVICES SERVICES CUSTOM_SERVICES" \
            create-container@10.15.0.4 | tee "$TMP_OUTPUT"
          
          OUTPUT=$(cat "$TMP_OUTPUT")
          rm "$TMP_OUTPUT"
          echo "CONTAINER_CREATED=true" >> $GITHUB_OUTPUT

          exit $?
        fi

     - name: Container Update on Branch Push
       if: github.event_name == 'push' && steps.create-lxc.outputs.CONTAINER_CREATED != 'true'
       run: |
          ssh -i ~/.ssh/id_rsa \
            -o SendEnv="CONTAINER_NAME PROXMOX_USERNAME PROXMOX_PASSWORD PROJECT_REPOSITORY PROJECT_BRANCH PROJECT_ROOT INSTALL_COMMAND START_COMMAND BUILD_COMMAND RUNTIME_LANGUAGE" \
            update-container@10.15.0.4
          exit $?

     - name: Container Deletion on Branch Deletion (Check)
       if: github.event_name == 'delete'
       run: |
          ssh -i ~/.ssh/id_rsa \
            -o SendEnv="PROXMOX_USERNAME PROXMOX_PASSWORD CONTAINER_NAME" delete-container@10.15.0.4
          exit $?