name: Deploy PR to LXC Container

# For now, only run when a PR is created or re-opened.
on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Enviornment Variables
        run: echo "Enviornment variables set"
        env:
          CONTAINER_NAME: pr-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}
          CONTAINER_PASSWORD: L3arNAtM1E!
          PROXMOX_USERNAME: mklema
          PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
          HTTP_PORT: 80
      - name: Add SSH Private Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.LXC_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
      - name: Run Create Container Script
        run: |
          echo "PROXMOX_USERNAME: $PROXMOX_USERNAME"
          ssh-keyscan opensource.mieweb.org >> ~/.ssh/known_hosts
          ssh -t -i ~/.ssh/id_ed25519 \
            -o SendEnv="CONTAINER_NAME CONTAINER_PASSWORD PROXMOX_USERNAME PROXMOX_PASSWORD HTTP_PORT" \
            create-container@opensource.mieweb.org
