name: Deploy PR to LXC Container

# For now, only run when a PR is created or re-opened.
on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  create-container:
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: pr-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}
      CONTAINER_PASSWORD: L3arNAtM1E!
      PROXMOX_USERNAME: mklema
      PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
      HTTP_PORT: 80
    steps:
      - name: Add SSH Private Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.LXC_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
      - name: Run Create Container Script
        id: create-lxc
        run: |
          ssh-keyscan opensource.mieweb.org >> ~/.ssh/known_hosts
          OUTPUT=$(ssh -i ~/.ssh/id_ed25519 \
            -o SendEnv="CONTAINER_NAME CONTAINER_PASSWORD PROXMOX_USERNAME PROXMOX_PASSWORD HTTP_PORT" \
            create-container@opensource.mieweb.org)
          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | grep "🛠️  SSH Access          : " | sed 's/🛠️  SSH Access          : //' | xargs -I{} echo "SSH_COMMAND={}" >> $GITHUB_OUTPUT
          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | grep "🔗  Domain Name         : " | sed 's/🔗  Domain Name         : //' | xargs -I{} echo "DOMAIN_NAME={}" >> $GITHUB_OUTPUT
          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | grep "🌐  Internal IP         : " | sed 's/🌐  Internal IP         : //' | xargs -I{} echo "INTERNAL_IP={}" >> $GITHUB_OUTPUT
          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | grep "📦  Container ID        : " | sed 's/📦  Container ID        : //' | xargs -I{} echo "CONTAINER_ID={}" >> $GITHUB_OUTPUT
      - name: Comment Container Details in PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const prNum = context.payload.pull_request.number;
            const comment = `
              🚀 **Container Deployed for this PR**

              Congratulations! This PR has been deployed to a live container on MIE's Proxmox Cluster.

              🔗 **Domain**: https://pr-mie-opensource-action-16.opensource.mieweb.org
              🛠️ **SSH Access**: ssh -p 2259 root@pr-mie-opensource-action-16.opensource.mieweb.org
              🌐 **Internal IP**: 10.15.73.194
              📦 **Container ID**: 119

              > To view container metrics, visit [https://opensource.mieweb.org:8006](https://opensource.mieweb.org:8006)
              <small>Note: Future commits to this PR will **<u>not be automatically</u>** updated on the container. This must be done manually.</small>
            `;
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: prNum,
              body: comment
            });

