name: Deploy PR to LXC Container

# For now, only run when a PR is created or re-opened.
on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  create-container:
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: pr-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}
      CONTAINER_PASSWORD: L3arNAtM1E!
      PROXMOX_USERNAME: mklema
      PROXMOX_PASSWORD: ${{ secrets.PROXMOX_PASSWORD }}
      HTTP_PORT: 80
    steps:
      - name: Add SSH Private Key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.LXC_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
      - name: Run Create Container Script
        id: create-lxc
        run: |
          ssh-keyscan opensource.mieweb.org >> ~/.ssh/known_hosts
          OUTPUT=$(ssh -i ~/.ssh/id_ed25519 \
            -o SendEnv="CONTAINER_NAME CONTAINER_PASSWORD PROXMOX_USERNAME PROXMOX_PASSWORD HTTP_PORT" \
            create-container@opensource.mieweb.org)
          STATUS=$?
          echo "EXIT_STATUS=$STATUS" >> $GITHUB_OUTPUT
          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | grep "🛠️  SSH Access          : " | sed 's/🛠️  SSH Access          : //' | xargs -I{} echo "SSH_COMMAND={}" >> $GITHUB_OUTPUT
          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | grep "🔗  Domain Name         : " | sed 's/🔗  Domain Name         : //' | xargs -I{} echo "DOMAIN_NAME={}" >> $GITHUB_OUTPUT
          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | grep "🌐  Internal IP         : " | sed 's/🌐  Internal IP         : //' | xargs -I{} echo "INTERNAL_IP={}" >> $GITHUB_OUTPUT
          echo "$OUTPUT" | sed 's/\x1b\[[0-9;]*m//g' | grep "📦  Container ID        : " | sed 's/📦  Container ID        : //' | xargs -I{} echo "CONTAINER_ID={}" >> $GITHUB_OUTPUT
      - name: Installing Octokit
      - uses: actions/checkout@v4
        run: npm install @octokit/rest 
        working-directory: .github/scripts
      - name: Comment Container Details in PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
          EXIT_STATUS: ${{ steps.create-lxc.outputs.EXIT_STATUS }}
          DOMAIN_NAME: ${{ steps.create-lxc.outputs.DOMAIN_NAME }}
          SSH_COMMAND: ${{ steps.create-lxc.outputs.SSH_COMMAND }}
          INTERNAL_IP: ${{ steps.create-lxc.outputs.INTERNAL_IP }}
          CONTAINER_ID: ${{ steps.create-lxc.outputs.CONTAINER_ID }}
        run: |
          node .github/scripts/writePRComment.js

